1 IF PEEK(&HF677)=128 THEN POKE&HD000,0:POKE&HF677,&HD0:RUN"robowres.bas"
2 KEYOFF:COLOR 15,1,1:CLS:PRINT"ROBOWREST    -    (C) Micronet 1988":PRINT"Disk version by JAM":PRINT"For MSX with at least 128KB":PRINT:PRINT "ROBOWREST IS LOADING ....";
3 FORI=1TO8:PRINT".";:BLOAD"robowres."+HEX$(I),R:NEXT
