cc1 inkey
cc2 inkey
as inkey.asm
del inkey.asm

cc1 maxpos
cc2 maxpos
as maxpos.asm
del maxpos.asm

cc1 kbcom
cc2 kbcom
as kbcom.asm
del kbcom.asm

cc1 kbcomr
cc2 kbcomr
as kbcomr.asm
del kbcomr.asm

cc1 plxset
cc2 plxset
as plxset.asm
del plxset.asm

cc1 plxpal
cc2 plxpal
as plxpal.asm
del plxpal.asm

cc1 nrsort
cc2 nrsort
as nrsort.asm
del nrsort.asm

cc1 bloads
cc2 bloads
as bloads.asm
del bloads.asm

cc1 bsaves
cc2 bsaves
as bsaves.asm
del bsaves.asm

as getkmode.asm

as setkmode.asm

