
; This source includes list of #ED starting byte combinations
; that doesn't have own code on this emulator.

zed00:
zed01:
zed02:
zed03:
zed04:
zed05:
zed06:
zed07:
zed08:
zed09:
zed0A:
zed0B:
zed0C:
zed0D:
zed0E:
zed0F:
zed10:
zed11:
zed12:
zed13:
zed14:
zed15:
zed16:
zed17:
zed18:
zed19:
zed1A:
zed1B:
zed1C:
zed1D:
zed1E:
zed1F:
zed20:
zed21:
zed22:
zed23:
zed24:
zed25:
zed26:
zed27:
zed28:
zed29:
zed2A:
zed2B:
zed2C:
zed2D:
zed2E:
zed2F:
zed30:
zed31:
zed32:
zed33:
zed34:
zed35:
zed36:
zed37:
zed38:
zed39:
zed3A:
zed3B:
zed3C:
zed3D:
zed3E:
zed3F:
zed4C:	EQU ZED44	;NEG *
zed4E:	EQU ZED46	;IM 0 *
zed54:	EQU ZED44	;NEG *
zed55:	EQU ZED45	;RETN *
zed5C:	EQU ZED44	;NEG *
zed5D:	EQU ZED45	;RETN *
zed63:	EQU ZZ22	;LD (nn),HL
zed64:	EQU ZED44	;NEG *
zed65:	EQU ZED45	;RETN *
zed66:	EQU ZED46	;IM 0 *
zed6B:	EQU ZZ2A	;LD HL,(nn)
zed6C:	EQU ZED44	;NEG *
zed6D:	EQU ZED45	;RETN *
zed6E:	EQU ZED46	;IM 0 *
zed74:	EQU ZED44	;NEG *
zed75:	EQU ZED45	;RETN *
zed76:	EQU ZED56	;IM 1 *
zed77:
zed7C:	EQU ZED44	;NEG *
zed7D:	EQU ZED45	;RETN *
zed7E:	EQU ZED5E	;IM 2 *
zed7F:
zed80:
zed81:
zed82:
zed83:
zed84:
zed85:
zed86:
zed87:
zed88:
zed89:
zed8A:
zed8B:
zed8C:
zed8D:
zed8E:
zed8F:
zed90:
zed91:
zed92:
zed93:
zed94:
zed95:
zed96:
zed97:
zed98:
zed99:
zed9A:
zed9B:
zed9C:
zed9D:
zed9E:
zed9F:
zedA1:
zedA4:
zedA5:
zedA6:
zedA7:
zedAC:
zedAD:
zedAE:
zedAF:
zedB4:
zedB5:
zedB6:
zedB7:
zedBC:
zedBD:
zedBE:
zedBF:
zedC0:
;zedC1: R800
zedC2:
;zedC3: R800
zedC4:
zedC5:
zedC6:
zedC7:
zedC8:
;zedC9: R800
zedCA:
zedCB:
zedCC:
zedCD:
zedCE:
zedCF:
zedD0:
;zedD1: R800
zedD2:
;zedD3: R800
zedD4:
zedD5:
zedD6:
zedD7:
zedD8:
;zedD9: R800
zedDA:
zedDB:
zedDC:
zedDD:
zedDE:
zedDF:
zedE0:
;zedE1: R800
zedE2:
;zedE3: R800
zedE4:
zedE5:
zedE6:
zedE7:
zedE8:
;zedE9: R800
zedEA:
zedEB:
zedEC:
zedED:
zedEE:
zedEF:
zedF0:
zedF1:
zedF2:
;zedF3: R800
zedF4:
zedF5:
zedF6:
zedF7:
zedF8:
;zedF9: R800
zedFA:
zedFB:
zedFC:
zedFD:
zedFE:
zedFF:
