var

(* This is set by the fixed point functions.  It is set true if there	*)
(* was an overflow							*)
	fixederror: boolean;

(* This the carry flag.  It is used by the fixed point functions.  The	*)
(* user's code doesn't play with it.					*)
	carry: carrytyp;

