#INCLUDE "STDIO-KU.RZ"

MAIN(ARGC,ARGV)
INT ARGC;
CHAR *ARGV[];
{
CHAR INFILE[20];
CHAR OUTFILE[20];
CHAR INSTRING[200];
CHAR OUTSTRING[200];
INT  POINT;
FILE *IUNIT,*OUNIT;

STRCPY (&INFILE,ARGV[1]);
IF ((POINT=INDEX(INFILE,"."))==-1)
	{
	STRCPY(&OUTFILE,&INFILE);
	STRCAT(&INFILE,".C");
	} 
ELSE STRNCPY(&OUTFILE,&INFILE,POINT);


STRCAT(&OUTFILE,".LOW");



IF ((IUNIT=FOPEN(&INFILE,"R"))==NULL)
	{
	PRINTF("OPEN ERROR : %S \r\n",&INFILE);
	EXIT();
	}

IF ((OUNIT=FOPEN(&OUTFILE,"W"))==NULL)
	{
	PRINTF("OPEN ERROR : %S \r\n",&OUTFILE);
	EXIT();
	}
 
WHILE (FGETS(&INSTRING,200,IUNIT)!=NULL)
	{
	INSTRING[STRLEN(&INSTRING)-1]=0X00;
	FOR (POINT=0;POINT<=(STRLEN(&INSTRING));POINT++)
	INSTRING[POINT]=TOLOWER(INSTRING[POINT]);


	FPUTS(&INSTRING,OUNIT);
	}
PUTC(0X1A,OUNIT);
EXIT();
}
