#INCLUDE "STDIO-KU.RZ"
#DEFINE TAB '	'

MAIN(ARGC,ARGV)
INT ARGC;
CHAR *ARGV[];
{
INT TABLEN,STRCNT,OSTRCNT,HCNT;
FILE *IUNIT,*OUNIT;
CHAR INFLAG,INCHAR[5],INC,ASCNT,INSTRING[300],OUTSTRING[300];

IF (ARGC < 3)
	{
	PRINTF("\r\nINPUT ERROR\r\nSYNTAX :=  [:Fx:]TABPOS INPUTFILE OUTPUTFILE [TABLENGTH]\r\n");
	RETURN;
	}
IF (ARGC==3)
	TABLEN=8;
ELSE
	{
	IF (((TABLEN=ATOI(ARGV[3]))<1) || (TABLEN > 10))
		{
		PRINTF("\r\nWRONG TABLENGTH (MIN. 1 , MAX. 10)\r\n");
		RETURN;
		}
	}
IF (OUNIT=FOPEN(ARGV[2],"R") != NULL)
	{
	INFLAG=1;
	WHILE (INFLAG)
		{
		PRINTF("\r\n%S ALREADY EXIST , DELETE ? (Y/N)\r\n",ARGV[2]);
		SCANF("%S",&INCHAR);
		SWITCH (INC=TOLOWER(INCHAR[0]))
			{
			CASE 'n' :	INFLAG=0;
					FCLOSE(OUNIT);
					RETURN;
					BREAK;

			CASE 'y' :	INFLAG=0;
					BREAK;
			}
		}
	}
FCLOSE(OUNIT);
IF ((OUNIT=FOPEN(ARGV[2],"W")) == NULL)
	{
	PRINTF("\r\nOPEN ERROR : %S\r\n",ARGV[2]);
	RETURN;
	}
IF ((IUNIT=FOPEN(ARGV[1],"R")) == NULL)
	{
	PRINTF("\r\nOPEN ERROR : %S\r\n",ARGV[1]);
	FCLOSE(OUNIT);
	RETURN;
	}
PRINTF("\r\n*");
ASCNT=0;
WHILE (FGETS(&INSTRING,300,IUNIT) != NULL)
	{
	OSTRCNT=0;
	FOR (STRCNT=0;STRCNT < (STRLEN(&INSTRING)-1);STRCNT++)
		{
		IF (INSTRING[STRCNT] != TAB)
			OUTSTRING[OSTRCNT++]=INSTRING[STRCNT];
		ELSE
			{
			HCNT=OSTRCNT;
			FOR (OSTRCNT;OSTRCNT<=(HCNT+(TABLEN-(HCNT%TABLEN))-1);OSTRCNT++)
				OUTSTRING[OSTRCNT]=' ';
			}
		}
	OUTSTRING[OSTRCNT]=0X00;
	FPUTS(&OUTSTRING,OUNIT);
	IF ((ASCNT++)>10)
		{
		PRINTF("*");
		ASCNT=0;
		}
	}
PUTC(0X1A,OUNIT);
FCLOSE(IUNIT);
FCLOSE(OUNIT);
}
