comment 'Code generated by RBC 1.3.3'
comment 'Copyright 1996,97 by Ricardo Bittencourt'

extern _putchar 

startup 

label $string0 
defs '67,111,109,112,105,108,101,100'
defs '32,98,121,32,82,66,67,32'
defs '67,111,112,121,114,105,103,104'
defs '116,32,49,57,57,54,44,57'
defs '55,32,98,121,32,82,105,99'
defs '97,114,100,111,32,66,105,116'
defs '116,101,110,99,111,117,114,116'
defs '0'

vari _a,0 

label _main
enter 
begin 
ldipi 2 
pushpi 
leaipp _a 
popsi 
ldsipp 
ldpppi 
end 
begin 
begin 
ldipi 48 
pushpi 
leaipp _a 
ldpppi 
popsi 
addsipi 
end 
savepi 
leaipp _putchar 
callpp 
restore #i 
end 
exit 
endf 

endcode 

