((Beatles ((John Lennon) (Paul McCartney) (George Harrison) (Ringo Starr)))) 
((inc John Lennon rythm_guitar)) 
((inc Paul McCartney bass_guitar)) 
((inc George Harrison solo_guitar)) 
((inc Ringo Starr drums)) 
((outdat2 ((X Y)|Z)) (PP X Y) (outdat2 Z)) 
((outdat2 ())) 
((Who X) (inc X Y Z) (PP Y)) 
((Who X) (inc Y X Z) (PP Y)) 
((Who X) (X Y) (outdat2 Y)) 
((Who X Y) (EQ X was) (EQ Y killed) (murder x y Z z) (PP x y was killed in Z in z)) 
((Play X Y) (inc X Y Z) (PP X Y plays on Z)) 
((Which X) (inc Y Z X) (PP Y Z 's)) 
((created Beatles (('Please Please Me' 61) ('Help!' 63) ('Revolver' 65) ('Rubber Soul' 64) ('White Album' 67) ('Let IT Be' 70) ('Hey 
de' 69) ('Hard Day's Night' 63) ('Yellow Submarine' 67) (Sergeant Pepper's Lonely Heart Club Band' 66) ('With The Beatles' 62)))) 
((record X) (created X Y) (type Y)) 
((type (X|Y)) (PP X) (type Y)) 
((type ())) 
((murder John Lennon New-York 1980)) 
((When X Y Z x) (EQ X was) (EQ Y killed) (murder Z x y z) (PP in z)) 
((Where X Y Z x) (EQ X was) (EQ Y killed) (murder Z x y z) (PP in y)) 
