((inf kingball blo стрелялка)) 
((inf pac-man blo лабиринт)) 
((inf woogijun blo лабиринт)) 
((inf azteka gm стрелялка)) 
((inf billiard gm спорт)) 
((inf alfasqu blo тренажор)) 
((inf ninjak blo стрелялка)) 
((inf pass737 blo тренажор)) 
((inf stenis gm спорт)) 
((inf rabbit gm лабиринт)) 
((inf pong gm спорт)) 
((inf football gm спорт)) 
((inf boxe gm спорт)) 
((inf baseball gm спорт)) 
((inf flappy blo лабиринт)) 
((inf colpax blo лабиринт)) 
((inf pin gm спорт)) 
((inf step-up blo лабиринт)) 
((inf becky blo лабиринт)) 
((inf bee&flouer blo прогулка)) 
((inf hopper blo прогулка)) 
((inf huperal blo спорт)) 
((inf rally-x blo лабиринт)) 
((inf athland blo прогулка)) 
((inf comicba blo прогулка)) 
((inf antaradv blo прогулка)) 
((inf macadamy blo лабиринт)) 
((inf puzzle blo мозаика)) 
((inf fire blo лабиринт)) 
((inf piramid blo лабиринт)) 
((inf snake gm лабиринт)) 
((inf funmouse gm лабиринт)) 
((inf cpu gm лабиринт)) 
((inf moriran blo лабиринт)) 
((games) (inf X Y Z) (PP X) FAIL) 
((what games) (inf X Y Z) (PP X - Z) FAIL) 
((is) (R X) (inf X Y Z) (PP X - Z)) 
((are) (R X) (PP X :) (inf Y Z X) (PP Y) FAIL) 
