((DI)(DEL# I1 I2 I3 inp inp1 title DI)
 (LPRES ADDCL DELCL KILL IF NOT LIST DICT OPEN CLOSE R P PP RF PF PPF
  EQ EXECUTE CL OR TIMES SUM LESS INT NUM VAR LST AT SAVE LOAD ? OPMOD
  RES CPRED CLS PRTALL GETB PUTB SETF GETF)
 (INV SYSTEM RESTART RESTART1 S# RS# SYSTEM1 EX L# I# V# CU#
  PRES ISPRES UNPRES LPRES LUNPRES D# LF# GE# CAT
  KILLAT KILLST KILLM DELX DELCLX ADDCLX TUNDEF VIS LMODX LMOD
  L1 O# DEL# M1 IN IN1 INP PROMPT LPX LPX1 sp1 sp2))
((SYST) (D#((SYST|x)|y))
 (CLS) (SYSTEM))
((SYSTEM)(RS# (RESTART))(SYSTEM1))
((RESTART)(GE# x y)(RESTART1 x y))
((RESTART1 -2 x)/(PP Сохраните базу данных)(SYSTEM1))
((RESTART1 -1 x)/(PP ?)(SYSTEM1))
((RESTART1 0 x)/(SYSTEM1))
((RESTART1 x y)(P error : x "     goal:" y)(PP)(SYSTEM1))
((S# EOF)(D#((INP|x)/(RF x1|y)|z))(CLOSE x1)(D#((PROMPT|x2)|y2))
 (PP - Конец EXECUTE)/)
((S# x)(AT x)(OR ((EQ x EOF))((EQ x bye))((EQ x BYE)))(RS#))
((S# ()))
((S# (x|y))/(AT x)(x|y))
((S# x)(AT x)(INP y)(x y))
((SYSTEM1)(RS#(RESTART))(PROMPT)(INP x)(S# x))
((PROMPT)(P _)(PUTB 1 8))
((INP x)(R x))
((EXECUTE x1)(OPEN x r x1)/(ADDCL((INP y)/(RF x y)(P y))0)
 (ADDCL ((PROMPT)/(PP)(P E.))0))
((EXECUTE x)(PP Файл не открывается))
((OPEN x (y z)|x1)/(NUM z)(O# x y|x1)(LF# x z))
((OPEN x y|x1)(O# x y|x1))
((EX|y)(LST y)/(EX1|y))
((EX)/)
((EX|y)(PP EX : неправильный список целей : y)ABORT)
((EX1 y|z)(LST y)/ y(EX|z))
((EX1 y|z)(VAR y)/(PP EX : переменная в качестве цели : (y|z))ABORT)
((EX1 y|z)/ y(EX|z))
((EX1))
((IF X Y Z) X /|Y)
((IF X Y Z) /|Z)
((IF X Y) X /|Y)
((IF X Y))
((IN|X) (IN1 0|X)) 
((IN1 X Y X Z Z|x) (NOT LESS X Y)) 
((IN1 X Y Z x y|z) (SUM X 1 X1) (IN1 X1 Y Z x|z)) 
((NOT|X)X / FAIL)
((NOT|X))
((CL ((X|Y)|Y1)x y)(AT X)(NOT EQ X /)(NOT EQ X NIL)(NUM x)(VAR y)
 (CPRED X Z)(IN x y ((X|Y)|Y1)|Z))
((CL x)(CL x 0 y))
((CL x y)(CL x y z))
((LIST ALL)(DICT x|y)(NOT EQ x #) (PP - Модуль x)FAIL)
((LIST ALL)(DICT # x10 x|y)/(L# | y)/)
((LIST x)(AT x)(CPRED x y)(NOT EQ y NIL)(PP)(L1|y))
((LIST x)/)
((L1 x|y)(P - x)(PP)/(L1|y))
((L1))
((L#)/)
((L# x|y)(LIST x)/(L# | y))
((DEL# X|Y)(D#((X|Z)|Z1))/(DEL# X|Y))
((DEL# X|Y)/(DEL# | Y))
((DEL#))
((INV X|Y)(I# X)/(INV | Y))
((INV))
((LPRES x|y)(PRES x)/(LPRES|y))
((LPRES))
((LUNPRES x|y)(UNPRES x)/(LUNPRES|y))
((LUNPRES))
((OR x|y)|x)
((OR x|y)(OR |y))
((EQ x x))
((PRINT ALL)(DICT # x y|z)(OPEN y1 w LST)(sp1 y1|z)(CLOSE y1))
((PRINT x)(CL((x|y)|z))(OPEN y1 w LST)(sp1 y1 x)(CLOSE y1))
((SAVE x)(DICT # x10 x2|x3)(OPEN y w x . p)(sp1 y|x3)(CLOSE y))
((sp1 y x|z)(CPRED x x1)/(sp2 y|x1)(sp1 y|z))
((sp1 y x|z)/(sp1 y|z))
((sp1 y))
((sp2 y x|z)(PPF y x)/(sp2 y|z))
((sp2|x))
((DELCL ((x|y)|z))/(D# ((x|y)|z)))
((DELCL x y)/(DN# x y))
((DELCL x)(AT x)(R y)(NUM y)(DN# x y))
((KILL ALL)(KILLM)/(DICT # x10 y|z)(DEL# |z)/(KILLST|z))
((KILL #)/)
((KILL x)(DICT x x10 y|z)/
 (LUNPRES|z)(DELCLX((DICT x x11 x3|x2)))(DEL#|x2)
 (VIS x|x3)(DEL#|x3)/(KILLST x|x3))
((KILL x)(RES x)/ FAIL)
((KILL x)(DEL# x)/(KILLAT x))
((KILLM)(DICT x|y)(KILL x)FAIL)
((KILLM))
((KILLST x1 x2 x3 x4 x5|y)/(KILLAT x1 x2 x3 x4 x5)/(KILLST|y))
((KILLST|x)(KILLAT|x))
((DELX|x)(DELCL|x)/)
((DELX|x))
((LOAD X) (OPEN Y r X . p) / (RF Y Z)(LPX1 Y Z) (CLOSE Y))
((LOAD X) (PP Файл не открывается))
((? x)|x)
((DICT # ()(ADDCL DELCL KILL IF NOT LIST DICT OPEN CLOSE R P PP RF PF PPF
     CL OR TIMES SUM LESS INT NUM VAR LST AT SAVE LOAD ?
     SETF GETF OPMOD RES)))
((LPX1 X ((Y|Z)|x)) (ADDCL ((Y|Z)|x) 32767) / (RF X Y5)(LPX1 X Y5)) 
((LPX1 X EOF) /) 
((LPX1 X CLMOD) (CU# Y)/(DICT # x10 Z|x) (DICT Y x11 z|y)
 (ADDCLX ((CU# #))0)(INV|y)(DELCLX CU# 0)(VIS Y|z)(DELCLX CU# 0)(VIS|x11)(LPRES|z)(VIS|x) (LPRES|z) 
 / (RF X Y5)(LPX1 X Y5))
((LPX1 X Y) (AT Y) / (LMOD X Y)) 
((TNDEF) /) 
((TNDEF X|Y) (ISPRES X) /(PP Предикат X уже определен)FAIL) 
((TNDEF X|Y) (CL ((X|Z)|x)) /(PP Предикат X уже определен)FAIL) 
((TNDEF X|Y) (TNDEF|Y)) 
((VIS X|Y) (V# X)/(VIS|Y)) 
((VIS X|Y)/(VIS |Y))
((VIS)) 
((LMOD X Y)(IF (DICT Y|y5)((KILL Y)))(RF X Z) (RF X x) (LMODX Y Z x X))
((LMODX X Y Z Z5) (DICT # x10 x|y) (TNDEF X|Y) (INV X|Y) (ADDCLX ((CU# X)) 0) (INV|y)
 (VIS |Z) (ADDCLX ((DICT X Z Y)))
 (VIS X|Y)/(RF Z5 Z6)(LPX1 Z5 Z6))
((LMODX x y z z1)(CLOSE z1))
((ADDCLX ((x|y)|z)|z1)(UNPRES x)(ADDCL ((x|y)|z)|z1)(PRES x))
((DELCLX ((x|y)|z)|z1)(UNPRES x)(DELCL ((x|y)|z)|z1)(PRES x)/)
((DELCLX x|y)(AT x)(UNPRES x)(DELCL x|y)(PRES x))
((OPMOD x)(DICT x x10 y|z)(LUNPRES|z)
 (DELCLX((DICT x|x1)))(VIS|z)
 (ADDCL((MODULE x y x10))))
((CAT x (y1|y2) z)/(CAT (y1|x) y2 z))
((CAT x () x))
((RES x)(ISPRES x))
((CU# #))
