lnk -u_main -eb__memory -tb0x100 -htr -o a:cpp.com b:crtx.o b:p0lib.80 b:libc.80
lnk -u_main -eb__memory -tb0x100 -htr -o a:cp1.com b:crtx.o b:p1lib.80 b:libc.80
lnk -u_main -eb__memory -tb0x100 -htr -o a:cp2.com b:crtx.o b:p2lib.80 b:libc.80
lnk -u_main -eb__memory -tb0x100 -htr -o a:rel.com b:crtx.o b:rel.o b:libc.80
lnk -u_main -eb__memory -tb0x100 -htr -o a:lord.com b:crtx.o b:lord.o b:libc.80
lnk -u_main -eb__memory -tb0x100 -htr -o a:lib.com b:crtx.o b:lib.o b:libc.80
lnk -u_main -eb__memory -tb0x100 -htr -o a:a80.com b:crtx.o b:asmlib.80 b:libc.80
