1 IF PEEK(&HF677)=128 THEN POKE&HD000,0:POKE&HF677,&HD0:RUN"spierrot.bas"
2 KEYOFF:COLOR 15,1,1:CLS:PRINT"SUPER PIERROT   -   (C) NIDECOM 1987    ":PRINT"Disk version by JAM":PRINT"For MSX with at least 128KB":PRINT:PRINT "SUPER PIERROT  IS LOADING ";
3 FORI=1TO8:PRINT".";:BLOAD"spierrot."+HEX$(I),R:NEXT
