((inf Angie Foster 74 (to_swim to_read rock_music))) 
((inf Judy Przybyla 75 (to_play_piano to_swim to_dance to_read))) 
((inf Ryan Callaway 75 (video_equipment computer_games))) 
((inf Jerod Marsalli 75 (food_Italian to_read computer_games))) 
((inf Jonathan England 74 (sports food_Italian animals))) 
((inf Kelli Johnson 74 (sports ice_cream music to_sleep))) 
((inf Matt Chiorini 75 (music guitar ice_cream food_American))) 
((inf Kirstin Schwind 74 (to_swim to_read photography to_write to_boat))) 
((inf Doug Mallery 74 (to_sleep to_read to_eat to_breathe to_sing to_screw to_arand to_shop to_do_stuff))) 
((year X) (NUM X) (inf Y Z X x) (PP Y Z was born in X) FAIL) 
((year X) (inf X Y Z x) (PP X Y was born in Z) FAIL) 
((year X)) 
((What X Y Z) (EQ X does) (EQ Z like) (out Y)) 
((out X) (inf X Y Z x) (PP X Y likes) (outlist x)) 
((outlist (X|Y)) (PP X) (outlist Y)) 
((outlist ())) 
((Who X Y) (EQ X likes) (inf Z x y z) (member Y z) (PP Z x likes Y) FAIL) 
((Who X Y) (EQ X is)(EQ Y hungry) (inf Z x y z) (food z) (PP Z x is) FAIL) 
((Who X Y)) 
((Who is X Y) (EQ X a) (EQ Y hooligan) (inf Z x y z) (member to_do_stuff z) (PP Z x likes to do stuff)) 
((member X (X|Y))) 
((member X (Y|Z)) (member X Z)) 
((food X) (member to_eat X)) 
((food X) (member food_American X)) 
((food X) (member food_Italian X)) 
((all group) (inf X Y Z x) (PP X Y) FAIL) 
((all group)) 
