((игра Pin_egg (лабиринт) (PIN.COM 2) (5 5))) 
((игра Pengwar (стрелялка) (PENGWAR2.BLO 2) (3 3))) 
((игра Panic_function (стрелялка) (COU.GM 2) (4 4))) 
((игра Snake_it (лабиринт) (SNAKIT.COM 2) (4 4))) 
((игра Heavy_Boxing (молотилка) (HBOXING.BLO 2) (2 2))) 
((игра Becky (лабиринт) (BECKY.BLO 3) (3 3))) 
((игра Chess (шахматы) (CHESS1.BLO 3) (4 4))) 
((игра Flappy (лабиринт стрелялка) (FLAPPY.BLO 3) (3 3))) 
((игра Chapion_Soccer (спорт) (FOOTBALL.BLO 3) (3 3))) 
((игра Warp_&_warp (лабиринт) (WARP.COM 3) (3 4))) 
((игра Pachcom (стрелялка) (PACHINKO.COM 3) (4 3))) 
((игра Super_Tennis (спорт) (STENNIS.BLO 3) (3 3))) 
((игра Ultra_chess (шахматы) (CHESS2.BLO 3) (3 3))) 
((игра Colpax (лабиринт) (COLPAX.BLO 3) (3 3))) 
((игра Lode_Runner (лабиринт) (LODRUN1.BLO 3) (4 4))) 
((игра Digdug (лабиринт) (DIGDAG.COM 3) (3 3))) 
((игра Volguard (леталка) (VOLGUARD.COM 3) (4 4))) 
((игра Tennis (спорт) (TENNIS.GM 3) (4 3))) 
((игра MSX_Soccer (спорт) (SOCCER.GM 3) (3 3))) 
((игра Ping-pong (спорт) (PONG.GM 3) (4 4))) 
((игра MSX_Basball (спорт) (BASEBALL.GM 3) (4 4))) 
((игра Rabbit (лабиринт) (RABBIT.GM 3) (4 49))) 

((игра alphaSquadron (леталка стрелялка) (ALPHASQU.BLO 1) (3 3))) 
((игра SkyJaguar (стрелялка) (SKYJAGU.BLO 1) (2 2))) 
((игра Ninjya_Kage (стрелялка) (NINJYAK.BLO 1) (2 3))) 
((игра Cannon_Figher (стрелялка) (CANNON.GM 1) (3 2))) 
((игра Eagle_Figher (леталка) (EAGLEFIG.GM 1) (3 3))) 
((игра Knightmare (стрелялка) (KNIGHT.COM 1) (4 4))) 
((игра Beamreder (стрелялка) ("BEAMRI.BAS " 1) (2 3))) 
((игра Scentipede (стрелялка) (SCENT.DAT 1) (2 2))) 
((игра Ski_Command (стрелялка) (SKICOMM.BLO))) 
((игра Warroid (стрелялка) (WARROID1.BLO 1) (3 3))) 
((игра Choplifter (стрелялка леталка) (CHOPLIF.BLO 1) (3 3))) 
((игра Galaxian (стрелялка) (GALAXIA.BLO 1) (2 2))) 
((игра BuckRogers (стрелялка леталка) (BUCKROG.BLO 1) (3 3))) 
((игра Mobile_Suit (бегалка стрелялка) (CUNDAM.BLO 1) (3 3))) 
((игра Clapton_2 (стрелялка) (CLAPTON.BLO 1) (1 1))) 
((игра Antarctic_Adventure (бегалка прыгалка) (ANTARADV.BLO 2) (4 4))) 
((игра Athletic_Land (бегалка) (ATHLAND.BLO 2) (3 3))) 
((игра Road_Faghter (ездилка) (ROADFAGH.BLO 2) (3 3))) 
((игра Circus_Charlie (стрелялка леталка) (CIRCUSCH.BLO 2) (2 2))) 
((игра Monky_Academy (считалка) (MACADEMI.BLO 2) (4 4))) 

