((игра alphaSquadron (леталка стрелялка) (ALPHASQU.BLO 1) (3 3))) 
((игра SkyJaguar (стрелялка) (SKYJAGU.BLO 1) (2 2))) 
((игра Ninjya_Kage (стрелялка) (NINJYAK.BLO 1) (2 3))) 
((игра Cannon_Figher (стрелялка) (CANNON.GM 1) (3 2))) 
((игра Eagle_Figher (леталка) (EAGLEFIG.GM 1) (3 3))) 
((игра Knightmare (стрелялка) (KNIGHT.COM 1) (4 4))) 
((игра Beamreder (стрелялка) ("BEAMRI.BAS " 1) (2 3))) 
((игра Scentipede (стрелялка) (SCENT.DAT 1) (2 2))) 
((игра Ski_Command (стрелялка) (SKICOMM.BLO))) 
((игра Warroid (стрелялка) (WARROID1.BLO 1) (3 3))) 
((игра Choplifter (стрелялка леталка) (CHOPLIF.BLO 1) (3 3))) 
((игра Galaxian (стрелялка) (GALAXIA.BLO 1) (2 2))) 
((игра BuckRogers (стрелялка леталка) (BUCKROG.BLO 1) (3 3))) 
((игра Mobile_Suit (бегалка стрелялка) (CUNDAM.BLO 1) (3 3))) 
((игра Clapton_2 (стрелялка) (CLAPTON.BLO 1) (1 1))) 
((игра Antarctic_Adventure (бегалка прыгалка) (ANTARADV.BLO 2) (4 4))) 
((игра Athletic_Land (бегалка) (ATHLAND.BLO 2) (3 3))) 
((игра Road_Faghter (ездилка) (ROADFAGH.BLO 2) (3 3))) 
((игра Circus_Charlie (стрелялка леталка) (CIRCUSCH.BLO 2) (2 2))) 
((игра Monky_Academy (считалка) (MACADEMI.BLO 2) (4 4))) 

