((inf Jerry Marsalli 36 Father San_Jose police_officer)) 
((inf Nancy Marsalli 37 Mother San_Francisco tupperware_dealer)) 
((inf Jerod Marsalli 13 Son Santa_Clara Paperboy_Umpire_Referee)) 
((inf Brian Marsalli 10 Son Santa_Clara schoolboy)) 
((inf Janelle Marsalli 7 Daughter Santa_Clara schoolgirl)) 
((Age X Y) (inf X Y Z x y z) (PP X Y is Z years old)) 
((Job X Y) (inf X Y Z x y z) (PP X Y is a z)) 
((Born X Y) (inf X Y Z x y z) (PP X Y was born in y)) 
((Fmember X Y) (inf X Y Z x y z) (PP X Y is x)) 
((Alljobs X) (inf Y X Z x y z) (PP Y z) FAIL) 
((Alljobs)) 
((Who X Y) (EQ X is) (inf Z x y Y z X1) (PP Z x X Y) FAIL) 
((Year X Y) (inf X Y Z x y z) (SUM X1 Z 1988) (PP X Y was born in X1)) 
