del libfix02.lzh
lhpack libfix02.lzh stdio.h stdlib.h errno.h fdoprnt.c
lhpack libfix02.lzh sleep.c time.c convtime.c strftime.c doprnt.c strdup.c strstr.c stristr.c strnstr.c strnistr.c strtok.c 
lhpack libfix02.lzh msxtime.as memcmp.as memcpy.as memmove.as memset.as memchr.as getch.as
lhpack libfix02.lzh frelop.as strnicmp.as stricmp.as strchr.as strrchr.as inout.as peekpoke.as signal.as rcsv.as

